print(2+2)
print(5/2)
print(5//2)
print(5**6)
print(5%2)
print(2+5*3-1+10/5)

weight_user = input('Enter you are weight? ')
height_user = input('Enter your height? ')
a = int(weight_user)
b = float(height_user)
calculate_BMI =(a)/(b ** 2)
print(calculate_BMI)