import turtle
turtle.getscreen()
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.lt(90)
turtle.forward(100)
turtle.lt(90)
turtle.forward(100)
turtle.lt(90)  
#turtle.shape("turtle")
print(turtle.shape())
turtle.exitonclick()